### PR TITLE
Use getBoundClientRect to get element offset

### PR DESCRIPTION
**Pull request by arkon**
This is a followup to #2, since I noticed that the previous solution doesn't work if the color picker is within a scrollable element that isn't the body itself.

### CODE REVIEW

**Comment by superguigui** [comment]
Hi Eugene, please resolve conflicts and commit again please

**Comment by arkon** [comment]
@superguigui Fixed!

**Comment by arkon** [comment]
@superguigui Will you be publishing an updated package on npm?

**Comment by superguigui** [comment]
I just published 0.0.7 with your last changes. Thank you !

**Pull request merged**
